#pragma once

#include "core/responsibility/responsibility_requirement.h"
#include "core/statechain/state_gene_fragment.h"

#include <stdexcept>
#include <string>

namespace asking_star::core::gene {

struct GeneHandle {
  std::string id;
  bool xing_allowed{true};
  bool ming_allowed{true};
  double inertia_score{1.0};

  [[nodiscard]] bool is_valid() const { return !id.empty(); }
};

struct Influence {
  std::string id;
  std::string capability;
  std::string reason;

  [[nodiscard]] bool is_valid() const {
    return !id.empty() && !capability.empty() && !reason.empty();
  }
};

struct GenerationDecision {
  asking_star::core::statechain::GenerationStatus status{
      asking_star::core::statechain::GenerationStatus::Pending};
  std::string reason;
  asking_star::core::responsibility::ResponsibilityRequirement responsibility;

  [[nodiscard]] bool is_valid() const {
    return !reason.empty() && responsibility.is_valid();
  }
};

class XingEvaluator {
 public:
  [[nodiscard]] bool allows(const GeneHandle& handle) const {
    return handle.xing_allowed;
  }
};

class MingEvaluator {
 public:
  [[nodiscard]] bool allows(const GeneHandle& handle) const {
    return handle.ming_allowed;
  }
};

class InertiaEngine {
 public:
  explicit InertiaEngine(double threshold = 0.5) : threshold_(threshold) {}

  [[nodiscard]] bool can_generate(const GeneHandle& handle) const {
    return handle.inertia_score >= threshold_;
  }

 private:
  double threshold_;
};

class GenerationGate {
 public:
  [[nodiscard]] GenerationDecision decide(
      const GeneHandle& handle, const Influence& influence,
      const asking_star::core::responsibility::ResponsibilityRequirement&
          requirement) const {
    if (!handle.is_valid() || !influence.is_valid() || !requirement.is_valid()) {
      throw std::invalid_argument("invalid generation gate input");
    }

    if (!xing_.allows(handle)) {
      return {asking_star::core::statechain::GenerationStatus::Rejected,
              "rejected by Xing / Intrinsic Constraints", requirement};
    }
    if (!ming_.allows(handle)) {
      return {asking_star::core::statechain::GenerationStatus::Rejected,
              "rejected by Ming / Runtime Trajectory", requirement};
    }
    if (!inertia_.can_generate(handle)) {
      return {asking_star::core::statechain::GenerationStatus::Pending,
              "pending by inertia", requirement};
    }
    return {asking_star::core::statechain::GenerationStatus::Generated,
            "generated by Sheng / State Generation Protocol", requirement};
  }

 private:
  XingEvaluator xing_;
  MingEvaluator ming_;
  InertiaEngine inertia_;
};

class GeneProtocol {
 public:
  [[nodiscard]] GenerationDecision evaluate(const GeneHandle& handle,
                                            const Influence& influence) const {
    const asking_star::core::responsibility::ResponsibilityRequirement
        requirement{influence.capability, influence.reason};
    return gate_.decide(handle, influence, requirement);
  }

  [[nodiscard]] GenerationDecision evaluate(
      const GeneHandle& handle, const Influence& influence,
      const asking_star::RuntimeTemperature& temperature) const {
    const asking_star::core::responsibility::ResponsibilityRequirement
        requirement{influence.capability, influence.reason};
    if (!temperature.is_valid()) {
      throw std::invalid_argument("invalid runtime temperature");
    }
    if (temperature.absolute_zero) {
      return {asking_star::core::statechain::GenerationStatus::Rejected,
              "rejected by AbsoluteZero / frozen gene lifecycle",
              requirement};
    }
    return gate_.decide(handle, influence, requirement);
  }

 private:
  GenerationGate gate_;
};

}  // namespace asking_star::core::gene
